<?php 

$title = 'Add new bug';
$this->headTitle($title);

$form = $this->bugForm;
$form->setAttribute('action', $this->url('bug', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('priority'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('summery'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();