<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('LemonPie Bugtracker'); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
      <?php if($this->zfcUserIdentity()){?>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">LemonPie</a>
                    <div class="nav-collapse collapse"> 
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                      	 	<li class="dropdown">
                      	 		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Bugs<b class="caret"></b></a>
                      	 		<ul class="dropdown-menu">
                      	 			<li><a href="">Create</a></li>
                      	 			<li><a href="">View all</a></li>
                      	 			<li><a href="">View mine</a></li>
                      	 		</ul>
                      	 	</li>
							<li class="dropdown">
                      	 		<a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects<b class="caret"></b></a>
                      	 		<ul class="dropdown-menu">
                      	 			<li><a href="">Create</a></li>
                      	 			<li><a href=">">View all</a></li>
                      	 			<li><a href="">View mine</a></li>
                      	 		</ul>
                      	 	</li>                      	 	
                            <li class=""><a href="">Members</a></li>
                        </ul>
                        <ul class="nav pull-right">
                        	<li class="divider-vertical" />
                        	<li class="dropdown">
                            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Hello, <?php echo $this->zfcUserDisplayName() ?>!<b class="caret"></b>
                              </a>
                            	<ul class="dropdown-menu">
                            		<li><a href="<?php echo $this->url('user/edit')?> ">Profile</a></li>
                            		<li><a href="<?php echo $this->url('user/logout') ?>">Logout</a></li>
                            		<li><a href="">Make LemonPie</a></li>
                            	</ul>
                            </li>
                            <li><a href="#banner" id="open-menu">More</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
      <?php } ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <dic id="footer">
                <p>&copy; 2005 - 2012 by LemonPie. All rights reserved.</p>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
